export const colorNames = [
    'rojo',
    'azul',
    'verde',
    'verde lima',
    'amarillo',
    'negro',
    'blanco',
    'gris',
    'gris claro',
    'gris oscuro',
    'naranja',
    'celeste',
    'violeta',
    'morado',
    'rosa',
    'fucsia',
    'marrón',
    'beige',
    'bordó',
    'turquesa',
    'dorado',
    'plateado',
    'azul marino',
    'verde oscuro',
    'verde claro',
    'mostaza',
    'salmon',
    'coral',
    'lavanda',
    'cian',
    'lila',
    'ocre'
];